"use client";
import { useEffect, useMemo, useState } from "react";
import {profitSummary} from "@/lib/crmTools";
import { createClient } from "@/lib/supabase/client";

type Customer = {user_id?:string;id:string;name:string;address:string;phone:string;email:string};
type Finding = {status:string;notes:string;photos:string[]};
type Package = {name:string;scope:string;price:number};
type Payload = {date?:string;findings?:Record<string,Finding>;revenue?:number;materials?:number;labor?:number;disposal?:number;other?:number;costType?:string;job?:string;packages?:Package[];provider?:string;start?:string;end?:string;terms?:string;files?:string[];lat?:number;lng?:number};
type RecordRow = {id:string;lead_id:string;kind:string;title:string;payload:Payload;created_at:string};
type Props = {customers:Customer[];userId:string|null;cloudMode:boolean;mode:string;initialCustomerId?:string;onOpen:(tab:string,customerId?:string,option?:Package)=>void};
const kinds:Record<string,string>={"Inspections":"inspection","Profit Calculator":"profit","Estimate Options":"options","Warranties":"warranty","Customer Map":"location"};
const inspectionItems=["Shingles / roof covering","Leaks / water damage","Flashing","Ventilation","Decking","Gutters / drainage","Storm damage"];
const usd=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n);
export default function BusinessTools({customers,userId,cloudMode,mode,initialCustomerId="",onOpen}:Props){
 const db=useMemo(()=>createClient(),[]);
 const [leadId,setLeadId]=useState(initialCustomerId);const [rows,setRows]=useState<RecordRow[]>([]);const [editing,setEditing]=useState<string|null>(null);const [title,setTitle]=useState("");const [payload,setPayload]=useState<Payload>({});const [files,setFiles]=useState<string[]>([]);const [jobs,setJobs]=useState<{id:string;title:string;lead_id:string}[]>([]);const [busy,setBusy]=useState(false);const [ready,setReady]=useState(false);const [message,setMessage]=useState("");const [reload,setReload]=useState(0);const [mapRecord,setMapRecord]=useState<string|null>(null);
 const kind=kinds[mode];const customer=customers.find(c=>c.id===leadId);const storageKey="starcrm.tools."+(userId||"local");
 useEffect(()=>{let active=true;setReady(false);setRows([]);setFiles([]);setJobs([]);setEditing(null);setPayload({});setTitle("");setMessage("");async function load(){try{if(cloudMode){if(!db||!userId)throw Error("Sign in first.");let all:RecordRow[]=[];for(let offset=0;;offset+=1000){const {data,error}=await db.from("crm_records").select("id,lead_id,kind,title,payload,created_at").eq("kind",kind).order("created_at",{ascending:false}).order("id").range(offset,offset+999);if(error)throw error;all.push(...data as RecordRow[]);if(data.length<1000)break;}if(active)setRows(all);
 if(leadId&&["inspection","warranty"].includes(kind)){const {data,error}=await db.storage.from("customer-files").list((customer?.user_id||userId)+"/"+leadId,{limit:1000});if(error)throw error;if(active)setFiles((data||[]).filter(f=>f.id).map(f=>f.name));}
 if(kind==="profit"){const {data,error}=await db.from("jobs").select("id,title,lead_id");if(error)throw error;if(active)setJobs(data||[]);}
 }else{const all=JSON.parse(localStorage.getItem(storageKey)||"[]") as RecordRow[];if(active){setRows(all.filter(r=>r.kind===kind));setJobs(JSON.parse(localStorage.getItem("richardcrm.jobs.v1")||"[]"));}}
 }catch(e){if(active)setMessage(e instanceof Error?e.message:"Could not load records.");}finally{if(active)setReady(true);}}void load();return()=>{active=false;};},[db,userId,cloudMode,kind,leadId,reload,storageKey,customer?.user_id]);
 function patch(change:Partial<Payload>){setPayload(p=>({...p,...change}));}
 function finding(name:string,change:Partial<Finding>){const old=payload.findings?.[name]||{status:"Not inspected",notes:"",photos:[]};patch({findings:{...payload.findings,[name]:{...old,...change}}});}
 async function save(){if(!customer||!title.trim()){setMessage("Choose a customer and enter a record title.");return;}
 const numbers=kind==="profit"?[payload.revenue||0,payload.materials||0,payload.labor||0,payload.disposal||0,payload.other||0]:kind==="options"?(payload.packages||[]).map(p=>p.price):[];
 if(numbers.some(n=>!Number.isFinite(n)||n<0||n>9999999999.99)){setMessage("Amounts must be valid nonnegative US dollar values.");return;}
 if(kind==="location"&&(!Number.isFinite(payload.lat)||!Number.isFinite(payload.lng)||Math.abs(payload.lat!)>90||Math.abs(payload.lng!)>180)){setMessage("Enter latitude between -90 and 90 and longitude between -180 and 180.");return;}
 if(kind==="options"&&((payload.packages||[]).length!==3||(payload.packages||[]).some(p=>!p.scope.trim()))){setMessage("Describe the scope for all three packages.");return;}
 if(kind==="warranty"&&(!payload.provider?.trim()||!payload.start||!payload.end||payload.end<payload.start)){setMessage("Enter the provider and valid coverage dates, with expiration after the start.");return;}
 if(kind==="profit"&&payload.job&&!jobs.some(j=>j.id===payload.job&&j.lead_id===leadId)){setMessage("Choose a job for this customer.");return;}
 setBusy(true);setMessage("");const storedPayload=kind==="inspection"?{...payload,findings:Object.fromEntries(inspectionItems.map(name=>[name,payload.findings?.[name]||{status:"Not inspected",notes:"",photos:[]}]))}:payload;
 const record:RecordRow={id:editing||crypto.randomUUID(),lead_id:leadId,kind,title:title.trim(),payload:storedPayload,created_at:rows.find(r=>r.id===editing)?.created_at||new Date().toISOString()};try{if(cloudMode){if(!db||!userId)throw Error("Sign in first.");const q=editing?db.from("crm_records").update({title:record.title,payload:storedPayload,updated_at:new Date().toISOString()}).eq("id",editing):db.from("crm_records").insert({...record,user_id:userId});const {error}=await q.select("id").single();if(error)throw error;}else{const all=JSON.parse(localStorage.getItem(storageKey)||"[]") as RecordRow[];localStorage.setItem(storageKey,JSON.stringify([record,...all.filter(r=>r.id!==record.id)]));}setRows(current=>[record,...current.filter(r=>r.id!==record.id)]);setEditing(null);setTitle("");setPayload({});setMessage("Saved.");}catch(e){setMessage(e instanceof Error?e.message:"Could not save.");}finally{setBusy(false);}}
 async function remove(record:RecordRow){if(!confirm("Delete this record? Attached uploads remain in Lead Files."))return;setBusy(true);try{if(cloudMode){if(!db)throw Error("Database unavailable.");const {error}=await db.from("crm_records").delete().eq("id",record.id).select("id").single();if(error)throw error;}else{const all=JSON.parse(localStorage.getItem(storageKey)||"[]") as RecordRow[];localStorage.setItem(storageKey,JSON.stringify(all.filter(r=>r.id!==record.id)));}setRows(r=>r.filter(x=>x.id!==record.id));if(editing===record.id){setEditing(null);setPayload({});setTitle("");}setMessage("Deleted.");}catch(e){setMessage(e instanceof Error?e.message:"Could not delete.");}finally{setBusy(false);}}
 async function viewFile(name:string){const popup=window.open("","_blank");if(!popup){setMessage("Allow popups to view the file.");return;}try{if(!db||!userId)throw Error("Sign in first.");const {data,error}=await db.storage.from("customer-files").createSignedUrl((customer?.user_id||userId)+"/"+leadId+"/"+name,60);if(error)throw error;popup.location.href=data.signedUrl;}catch(e){popup.close();setMessage(e instanceof Error?e.message:"File unavailable.");}}
 function filePicker(selected:string[],update:(names:string[])=>void,photos=false){const choices=files.filter(f=>!photos||/\.(jpg|jpeg|png|webp)$/i.test(f));return <div className="field"><label>Select existing {photos?"photos":"documents / uploads"}</label><select multiple aria-label={photos?"Attach photos":"Attach documents"} value={selected} onChange={e=>update(Array.from(e.target.selectedOptions,o=>o.value))}>{choices.map(f=><option key={f} value={f}>{f}</option>)}</select><small className="muted">Upload files in Lead Files first. Use Ctrl / Command to select several.</small></div>;}
 const packages=payload.packages||["Good","Better","Best"].map(name=>({name,scope:"",price:0}));
 const {costs,profit,margin}=profitSummary(payload);
 const visible=rows.filter(r=>!leadId||r.lead_id===leadId);
 return <div className="card"><h2>{mode}</h2><div className="roofToolbar"><div className="field"><label htmlFor="tools-customer">Customer / property</label><select id="tools-customer" disabled={busy} value={leadId} onChange={e=>setLeadId(e.target.value)}><option value="">Choose a customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name} — {c.address}</option>)}</select></div><button className="mini" disabled={busy} onClick={()=>setReload(n=>n+1)}>Refresh records / uploads</button></div>
 {message&&<p role="status" className="notice">{message}</p>}
 <fieldset disabled={busy||!ready||!customer} style={{border:0,padding:0}}><legend>{editing?"Edit record":"New record"}</legend><div className="field"><label htmlFor="tool-title">Title</label><input id="tool-title" maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></div>
 {kind==="inspection"&&<><div className="field"><label htmlFor="inspection-date">Inspection date</label><input id="inspection-date" type="date" value={payload.date||""} onChange={e=>patch({date:e.target.value})}/></div>{inspectionItems.map(name=>{const f=payload.findings?.[name]||{status:"Not inspected",notes:"",photos:[]};return <div className="card" key={name} style={{marginTop:12}}><h3>{name}</h3><select aria-label={name+" condition"} value={f.status} onChange={e=>finding(name,{status:e.target.value})}>{["Not inspected","Good","Monitor","Repair needed","Replace needed"].map(s=><option key={s}>{s}</option>)}</select><div className="field"><label>{name} notes</label><textarea aria-label={name+" notes"} value={f.notes} onChange={e=>finding(name,{notes:e.target.value})}/></div>{filePicker(f.photos,photos=>finding(name,{photos}),true)}</div>;})}</>}
 {kind==="profit"&&<><p className="muted">Projected or recorded costs against the contract price. Payment receipts remain in Invoices.</p><div className="field"><label htmlFor="profit-job">Job (optional)</label><select id="profit-job" value={payload.job||""} onChange={e=>patch({job:e.target.value})}><option value="">Customer-level calculation</option>{jobs.filter(j=>j.lead_id===leadId).map(j=><option key={j.id} value={j.id}>{j.title}</option>)}</select></div><div className="field"><label htmlFor="cost-type">Cost basis</label><select id="cost-type" value={payload.costType||"Projected"} onChange={e=>patch({costType:e.target.value})}><option>Projected</option><option>Recorded actual costs</option></select></div><div className="formGrid">{(["revenue","materials","labor","disposal","other"] as const).map(key=><div className="field" key={key}><label htmlFor={"cost-"+key}>{key==="revenue"?"Contract price":key} ($)</label><input id={"cost-"+key} type="number" min="0" step="0.01" value={payload[key]??""} onChange={e=>patch({[key]:Number(e.target.value)})}/></div>)}</div><div className="kpi">Total cost <strong>{usd(costs)}</strong></div><div className="kpi">Profit / loss <strong>{usd(profit)}</strong></div><div className="kpi">Profit margin <strong>{margin!==null?margin.toFixed(1)+"%":"—"}</strong></div></>}
 {kind==="options"&&<><p className="muted">Save three alternative scopes and prices. These are choices, so their prices are never added together. Build the chosen itemized quote in Estimates.</p><div className="grid toolPackages">{packages.map((p,i)=><div className="card" key={i}><h3>{p.name}</h3><div className="field"><label htmlFor={"package-name-"+i}>Package name</label><input id={"package-name-"+i} value={p.name} onChange={e=>patch({packages:packages.map((x,j)=>j===i?{...x,name:e.target.value}:x)})}/></div><div className="field"><label htmlFor={"package-scope-"+i}>Materials, scope and benefits</label><textarea id={"package-scope-"+i} value={p.scope} onChange={e=>patch({packages:packages.map((x,j)=>j===i?{...x,scope:e.target.value}:x)})}/></div><div className="field"><label htmlFor={"package-price-"+i}>Price ($)</label><input id={"package-price-"+i} type="number" min="0" step="0.01" value={p.price} onChange={e=>patch({packages:packages.map((x,j)=>j===i?{...x,price:Number(e.target.value)}:x)})}/></div></div>)}</div></>}
 {kind==="warranty"&&<><div className="field"><label htmlFor="warranty-provider">Manufacturer / contractor</label><input id="warranty-provider" value={payload.provider||""} onChange={e=>patch({provider:e.target.value})}/></div><div className="formGrid">{(["start","end"] as const).map(key=><div className="field" key={key}><label htmlFor={"warranty-"+key}>{key==="start"?"Coverage starts / job completion":"Expiration date"}</label><input id={"warranty-"+key} type="date" value={payload[key]||""} onChange={e=>patch({[key]:e.target.value})}/></div>)}</div><div className="field"><label htmlFor="warranty-terms">Coverage, exclusions and claim contact</label><textarea id="warranty-terms" value={payload.terms||""} onChange={e=>patch({terms:e.target.value})}/></div>{filePicker(payload.files||[],files=>patch({files}))}</>}
 {kind==="location"&&<><p className="muted">Save verified coordinates from your map app. Addresses are not located automatically.</p><a target="_blank" rel="noreferrer" href={"https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(customer?.address||"San Antonio TX")}>Find this address / copy coordinates</a><div className="formGrid">{(["lat","lng"] as const).map(key=><div className="field" key={key}><label htmlFor={"pin-"+key}>{key==="lat"?"Latitude":"Longitude"}</label><input id={"pin-"+key} type="number" step="any" value={payload[key]??""} onChange={e=>patch({[key]:e.target.value===""?undefined:Number(e.target.value)})}/></div>)}</div></>}
 <div className="roofToolbar"><button className="btn" onClick={save}>{busy?"Saving…":"Save "+mode.toLowerCase()}</button>{editing&&<button className="mini" onClick={()=>{setEditing(null);setTitle("");setPayload({});}}>Cancel edit</button>}</div></fieldset>
 {kind==="location"&&<p className="muted">Choose any saved property below to display its pin and get directions.</p>}
 <h3 style={{marginTop:24}}>Saved records</h3>{!ready?<p>Loading…</p>:!visible.length?<p className="muted">No saved records.</p>:visible.map(r=><div className="card" style={{marginTop:12}} key={r.id}><h3>{r.title}</h3><p className="muted">{customers.find(c=>c.id===r.lead_id)?.name}</p>{r.kind==="inspection"&&<><p>{r.payload.date||"Date not set"}</p>{Object.entries(r.payload.findings||{}).map(([name,f])=><div key={name}><strong>{name}: {f.status}</strong><p style={{whiteSpace:"pre-wrap"}}>{f.notes}</p>{f.photos.map(file=><button key={file} className="mini" disabled={busy} onClick={()=>{void viewFileFor(r.lead_id,file);}}>View photo: {file}</button>)}</div>)}</>}
 {r.kind==="profit"&&(()=>{const p=r.payload;const {costs:c,profit,margin}=profitSummary(p);return <p>{p.costType||"Projected"} — Contract: {usd(p.revenue||0)} · Costs: {usd(c)} · Profit: {usd(profit)} · Margin: {margin!==null?margin.toFixed(1)+"%":"—"}</p>;})()}
 {r.kind==="options"&&<div className="grid toolPackages">{r.payload.packages?.map((p,i)=><div key={i}><h3>{p.name} — {usd(p.price)}</h3><p style={{whiteSpace:"pre-wrap"}}>{p.scope}</p><button className="mini" onClick={()=>onOpen("Estimates",r.lead_id,p)}>Build quote from this option</button></div>)}</div>}
 {r.kind==="warranty"&&<><p>{r.payload.provider} · {r.payload.start} to {r.payload.end} · {warrantyState(r.payload.end)}</p><p style={{whiteSpace:"pre-wrap"}}>{r.payload.terms}</p>{r.payload.files?.map(f=><button className="mini" key={f} onClick={()=>void viewFileFor(r.lead_id,f)}>View {f}</button>)}</>}
 {r.kind==="location"&&<><button className="mini" onClick={()=>setMapRecord(mapRecord===r.id?null:r.id)}>{mapRecord===r.id?"Hide map":"Show property pin"}</button>{mapRecord===r.id&&<iframe title={r.title+" property map"} loading="lazy" style={{width:"100%",height:300,border:0,borderRadius:12}} src={mapUrl(r.payload.lat!,r.payload.lng!)}/>}<a target="_blank" rel="noreferrer" href={"https://www.google.com/maps/dir/?api=1&destination="+r.payload.lat+","+r.payload.lng}>Directions</a></>}
 <div className="roofToolbar"><button className="mini" disabled={busy} onClick={()=>{if(leadId!==r.lead_id){setMessage("Choose this record’s customer before editing.");return;}setEditing(r.id);setTitle(r.title);setPayload(r.payload);window.scrollTo({top:0,behavior:"smooth"});}}>Edit</button><button className="mini" disabled={busy} onClick={()=>void remove(r)}>Delete</button>{r.kind==="options"&&<button className="mini" onClick={()=>onOpen("Estimates",r.lead_id)}>Open estimate builder</button>}</div></div>)}
 </div>;
 async function viewFileFor(customerId:string,name:string){if(customerId===leadId){await viewFile(name);return;}const popup=window.open("","_blank");if(!popup){setMessage("Allow popups to view files.");return;}try{if(!db||!userId)throw Error("Sign in first.");const {data,error}=await db.storage.from("customer-files").createSignedUrl((customers.find(c=>c.id===customerId)?.user_id||userId)+"/"+customerId+"/"+name,60);if(error)throw error;popup.location.href=data.signedUrl;}catch(e){popup.close();setMessage(e instanceof Error?e.message:"Could not view file.");}}
}
function warrantyState(end?:string){if(!end)return "Expiration unknown";const now=new Date();const today=new Date(now.getFullYear(),now.getMonth(),now.getDate());const expiry=new Date(end+"T00:00:00");const days=Math.round((expiry.getTime()-today.getTime())/86400000);return days<0?"Expired":days<=30?"Expires in "+days+" days":"Active";}
function mapUrl(lat:number,lng:number){return "https://www.openstreetmap.org/export/embed.html?bbox="+[lng-.015,lat-.01,lng+.015,lat+.01].join("%2C")+"&layer=mapnik&marker="+lat+"%2C"+lng;}
