"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Customer={id:string;name:string;address:string};
type Kind="Personal"|"Appointment"|"Follow-up"|"Installation";
type Event={id:string;title:string;day:string;time:string;kind:Kind;details:string;completed:boolean;customerId?:string};
type Personal={id:string;title:string;task_date:string;task_time:string|null;notes:string;completed:boolean};
type Activity={id:string;lead_id:string;kind:string;title:string;details:string;due_at:string|null;completed:boolean};
type Job={id:string;lead_id:string;title:string;scheduled_date:string|null;status:string;crew:string;notes:string};
const colors:Record<Kind,string>={Personal:"#7357b5",Appointment:"#156b9a","Follow-up":"#a45809",Installation:"#247442"};
const kinds=Object.keys(colors) as Kind[];
function dateKey(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;}
function parseDay(day:string){return new Date(Number(day.slice(0,4)),Number(day.slice(5,7))-1,Number(day.slice(8,10)));}
export default function Calendar({customers,userId,cloudMode,onOpen}:{customers:Customer[];userId:string|null;cloudMode:boolean;onOpen:(tab:string,customerId?:string,day?:string)=>void}){
 const db=useMemo(()=>createClient(),[]);const [month,setMonth]=useState(()=>{const now=new Date();return new Date(now.getFullYear(),now.getMonth(),1);});const [selected,setSelected]=useState(()=>dateKey(new Date()));const [events,setEvents]=useState<Event[]>([]);const [loading,setLoading]=useState(true);const [ready,setReady]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [filters,setFilters]=useState<Kind[]>(kinds);const [showCompleted,setShowCompleted]=useState(false);const [addOpen,setAddOpen]=useState(false);const [refresh,setRefresh]=useState(0);
 const monthKey=dateKey(month).slice(0,7);
 useEffect(()=>{let active=true;setEvents([]);setLoading(true);setReady(false);setError("");async function load(){try{const first=new Date(month.getFullYear(),month.getMonth(),1);const next=new Date(month.getFullYear(),month.getMonth()+1,1);let personal:Personal[]=[];let activity:Activity[]=[];let jobs:Job[]=[];if(cloudMode){if(!db||!userId)throw new Error("Sign in to view your calendar.");const results=await Promise.all([db.from("personal_tasks").select("id,title,task_date,task_time,notes,completed").gte("task_date",dateKey(first)).lt("task_date",dateKey(next)),db.from("customer_activity").select("id,lead_id,kind,title,details,due_at,completed").in("kind",["appointment","task"]).gte("due_at",first.toISOString()).lt("due_at",next.toISOString()),db.from("jobs").select("id,lead_id,title,scheduled_date,status,crew,notes").gte("scheduled_date",dateKey(first)).lt("scheduled_date",dateKey(next)).neq("status","Cancelled")]);for(const result of results)if(result.error)throw result.error;personal=results[0].data as Personal[];activity=results[1].data as Activity[];jobs=results[2].data as Job[];}else{personal=JSON.parse(localStorage.getItem("richardcrm.personal-tasks.v1")||"[]");jobs=JSON.parse(localStorage.getItem("richardcrm.jobs.v1")||"[]");}
 const collected:Event[]=[...personal.map(task=>({id:"personal-"+task.id,title:task.title,day:task.task_date,time:task.task_time?.slice(0,5)||"",kind:"Personal" as Kind,details:task.notes,completed:task.completed})),...activity.filter(item=>item.due_at).map(item=>{const due=new Date(item.due_at!);return{id:"activity-"+item.id,title:item.title,day:dateKey(due),time:due.toLocaleTimeString("en-US",{hour:"2-digit",minute:"2-digit",hour12:false}),kind:(item.kind==="appointment"?"Appointment":"Follow-up") as Kind,details:item.details,completed:item.completed,customerId:item.lead_id};}),...jobs.filter(job=>job.scheduled_date&&job.status!=="Cancelled").map(job=>({id:"job-"+job.id,title:job.title,day:job.scheduled_date!,time:"",kind:"Installation" as Kind,details:`${job.status}\nCrew: ${job.crew||"Not assigned"}\n${job.notes}`,completed:job.status==="Completed",customerId:job.lead_id}))];if(active){setEvents(collected.filter(event=>event.day.startsWith(monthKey)));setReady(true);}}catch(error){if(active)setError(error instanceof Error?error.message:"Could not load calendar.");}finally{if(active)setLoading(false);}}void load();return()=>{active=false;};},[monthKey,month,db,userId,cloudMode,refresh]);
 function move(delta:number){const next=new Date(month.getFullYear(),month.getMonth()+delta,1);setMonth(next);setSelected(dateKey(next));setAddOpen(false);}
 async function add(form:FormData){if(busy)return;setBusy(true);setError("");try{const title=String(form.get("title")||"").trim();if(!title)throw new Error("Enter a task name.");const task:Personal={id:crypto.randomUUID(),title,task_date:selected,task_time:String(form.get("time")||"")||null,notes:String(form.get("notes")||""),completed:false};if(cloudMode){if(!db||!userId)throw new Error("Sign in before saving.");const {error}=await db.from("personal_tasks").insert({...task,user_id:userId});if(error)throw error;}else{const all=JSON.parse(localStorage.getItem("richardcrm.personal-tasks.v1")||"[]");localStorage.setItem("richardcrm.personal-tasks.v1",JSON.stringify([...all,task]));}setAddOpen(false);setRefresh(value=>value+1);}catch(error){setError(error instanceof Error?error.message:"Could not save task.");}finally{setBusy(false);}}
 const visible=events.filter(event=>filters.includes(event.kind)&&(showCompleted||!event.completed));const daily=visible.filter(event=>event.day===selected).sort((a,b)=>(a.time||"99").localeCompare(b.time||"99"));const offset=new Date(month.getFullYear(),month.getMonth(),1).getDay();const days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();const cells=Math.ceil((offset+days)/7)*7;
 return <div className="card"><h2>Calendar</h2><p className="muted">Personal tasks, customer appointments, follow-ups and installations together. Appointment times use this device’s time zone; personal times and installation dates stay as entered.</p><div className="roofToolbar"><button className="btn secondary" disabled={busy} aria-label="Previous month" onClick={()=>move(-1)}>← Previous</button><strong aria-live="polite">{month.toLocaleDateString("en-US",{month:"long",year:"numeric"})}</strong><button className="btn secondary" disabled={busy} aria-label="Next month" onClick={()=>move(1)}>Next →</button><button className="btn secondary" disabled={busy} onClick={()=>{const now=new Date();setMonth(new Date(now.getFullYear(),now.getMonth(),1));setSelected(dateKey(now));setAddOpen(false);}}>Today</button><button className="mini" disabled={busy||loading} onClick={()=>setRefresh(value=>value+1)}>Refresh</button></div><div className="roofToolbar" style={{margin:"16px 0"}}>{kinds.map(kind=><label key={kind} style={{color:colors[kind]}}><input type="checkbox" checked={filters.includes(kind)} onChange={event=>setFilters(current=>event.target.checked?[...current,kind]:current.filter(item=>item!==kind))}/> {kind}</label>)}<label><input type="checkbox" checked={showCompleted} onChange={event=>setShowCompleted(event.target.checked)}/> Show completed</label></div>{error&&<p className="notice" role="alert">{error}</p>}{loading&&<p role="status">Loading calendar…</p>}
 <div style={{overflowX:"auto"}}><div style={{display:"grid",gridTemplateColumns:"repeat(7,minmax(80px,1fr))",minWidth:560,gap:4}}>{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(day=><strong key={day} style={{textAlign:"center",padding:8}}>{day}</strong>)}{Array.from({length:cells},(_,index)=>{const number=index-offset+1;if(number<1||number>days)return <div key={index} aria-hidden="true"/>;const day=dateKey(new Date(month.getFullYear(),month.getMonth(),number));const entries=visible.filter(event=>event.day===day);return <button key={day} type="button" disabled={busy} aria-pressed={selected===day} aria-label={`${parseDay(day).toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric",year:"numeric"})}, ${entries.length} events`} onClick={()=>{setSelected(day);setAddOpen(false);}} style={{minHeight:105,textAlign:"left",padding:8,border:selected===day?"2px solid #d98b13":"1px solid #ccd2da",borderRadius:8,background:selected===day?"#fff5df":"#fff",color:"#172334",cursor:"pointer",overflow:"hidden"}}><strong>{number}{day===dateKey(new Date())?" · Today":""}</strong>{entries.slice(0,3).map(event=><div key={event.id} style={{fontSize:11,marginTop:4,color:colors[event.kind],whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{event.time&&event.time+" "}{event.title}</div>)}{entries.length>3&&<span className="small">+{entries.length-3} more</span>}</button>;})}</div></div>
 <h3 style={{marginTop:24}}>{parseDay(selected).toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric",year:"numeric"})}</h3><div className="roofToolbar"><button className="btn" disabled={busy||!ready} onClick={()=>setAddOpen(true)}>Add personal task</button><button className="btn secondary" disabled={busy} onClick={()=>onOpen("Daily Schedule",undefined,selected)}>Manage personal tasks</button><button className="btn secondary" disabled={busy} onClick={()=>onOpen("Customer Workspace")}>Schedule customer appointment</button></div>
 {addOpen&&<form key={selected} action={add}><fieldset disabled={busy} style={{border:0,padding:0}}><div className="field"><label htmlFor="calendar-title">Personal task</label><input id="calendar-title" name="title" required maxLength={200}/></div><div className="field"><label htmlFor="calendar-time">Time (optional)</label><input id="calendar-time" name="time" type="time"/></div><div className="field"><label htmlFor="calendar-notes">Notes</label><textarea id="calendar-notes" name="notes"/></div><div className="roofToolbar"><button className="btn">Save task for this day</button><button type="button" className="btn secondary" onClick={()=>setAddOpen(false)}>Cancel</button></div></fieldset></form>}
 {!loading&&ready&&(!daily.length?<p className="muted">No events for this day with the selected filters.</p>:daily.map(event=><div key={event.id} className="card" style={{borderLeft:`4px solid ${colors[event.kind]}`,marginTop:12}}><strong>{event.title}{event.completed?" · Complete":""}</strong><p className="small muted">{event.kind} · {event.time||"Any time"}{event.customerId?" · "+(customers.find(customer=>customer.id===event.customerId)?.name||"Customer"):""}</p>{event.details&&<p style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere"}}>{event.details}</p>}<button className="mini" onClick={()=>onOpen(event.kind==="Personal"?"Daily Schedule":event.kind==="Installation"?"Jobs":"Customer Workspace",event.customerId,event.day)}>Open / edit {event.kind=== "Personal"?"task":event.kind==="Installation"?"job":"customer activity"}</button></div>))}<p className="small muted" style={{marginTop:20}}>The calendar shows saved dated items. Undated jobs and tasks do not appear. No email, text, push reminders or external calendar synchronization are enabled.</p></div>;
}
