"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Quote={id:string;status:string;created_at:string;items:{quantity:number;rate:number}[]};
type Job={id:string;title:string;status:string;scheduled_date:string|null;crew:string};
type Invoice={id:string;job_id:string;number:string;total_cents:number;due_date:string|null};
type Payment={invoice_id:string;amount_cents:number};
const dollars=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(value);
export default function CustomerOverview({customerId,userId,onOpen}:{customerId:string;userId:string|null;onOpen:(tab:string)=>void}){
 const db=useMemo(()=>createClient(),[]);const [quotes,setQuotes]=useState<Quote[]>([]);const [jobs,setJobs]=useState<Job[]>([]);const [invoices,setInvoices]=useState<Invoice[]>([]);const [payments,setPayments]=useState<Payment[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{let active=true;setQuotes([]);setJobs([]);setInvoices([]);setPayments([]);setError("");setLoading(true);async function load(){try{if(!db||!userId)throw new Error("Sign in to load this customer’s overview.");const [quoteResult,jobResult]=await Promise.all([db.from("estimates").select("id,status,created_at,items").eq("lead_id",customerId).order("created_at",{ascending:false}),db.from("jobs").select("id,title,status,scheduled_date,crew").eq("lead_id",customerId).order("created_at",{ascending:false})]);if(quoteResult.error)throw quoteResult.error;if(jobResult.error)throw jobResult.error;const jobRows=jobResult.data as Job[];let invoiceRows:Invoice[]=[];let paymentRows:Payment[]=[];if(jobRows.length){const result=await db.from("invoices").select("id,job_id,number,total_cents,due_date").in("job_id",jobRows.map(job=>job.id));if(result.error)throw result.error;invoiceRows=result.data as Invoice[];if(invoiceRows.length){const result=await db.from("invoice_payments").select("invoice_id,amount_cents").in("invoice_id",invoiceRows.map(invoice=>invoice.id));if(result.error)throw result.error;paymentRows=result.data as Payment[];}}if(active){setQuotes(quoteResult.data as Quote[]);setJobs(jobRows);setInvoices(invoiceRows);setPayments(paymentRows);}}catch(error){if(active)setError(error instanceof Error?error.message:"Could not load overview.");}finally{if(active)setLoading(false);}}void load();return()=>{active=false;};},[customerId,userId,db]);
 const received=(id:string)=>payments.filter(payment=>payment.invoice_id===id).reduce((sum,payment)=>sum+payment.amount_cents,0);
 const outstanding=invoices.reduce((sum,invoice)=>sum+Math.max(0,invoice.total_cents-received(invoice.id)),0);
 const overpayments=invoices.reduce((sum,invoice)=>sum+Math.max(0,received(invoice.id)-invoice.total_cents),0);
 return <div className="card" style={{gridColumn:"1 / -1"}}><h2>Customer overview</h2><div className="roofToolbar"><button className="btn" onClick={()=>onOpen("Estimates")}>Create / view estimates</button><button className="btn secondary" onClick={()=>onOpen("Jobs")}>Create / view jobs</button><button className="btn secondary" onClick={()=>onOpen("Invoices")}>View invoices / record payment</button></div>{loading?<p role="status">Loading customer overview…</p>:error?<p className="notice" role="alert">{error}</p>:<><div className="kpi"><span>Total balance due across this customer’s invoices</span><strong>{dollars(outstanding/100)}</strong></div>{overpayments>0&&<p>Overpayments recorded: {dollars(overpayments/100)}. These have not been applied to other invoices.</p>}<h3>Estimates</h3>{!quotes.length?<p className="muted">No estimates yet.</p>:quotes.map(quote=><div className="kpi" key={quote.id}><span>{new Date(quote.created_at).toLocaleDateString()} · {quote.status||"Draft"}</span><strong>{dollars(quote.items.reduce((sum,item)=>sum+Math.round(item.quantity*item.rate*100),0)/100)}</strong></div>)}<h3>Jobs</h3>{!jobs.length?<p className="muted">No jobs yet.</p>:jobs.map(job=><div className="card" key={job.id} style={{marginTop:8}}><strong>{job.title} · {job.status}</strong><p className="muted">Installation: {job.scheduled_date||"Not scheduled"}<br/>Crew: {job.crew||"Not assigned"}</p></div>)}<h3>Invoices</h3>{!invoices.length?<p className="muted">No invoices yet.</p>:invoices.map(invoice=><div className="card" key={invoice.id} style={{marginTop:8}}><strong>Invoice {invoice.number} · {jobs.find(job=>job.id===invoice.job_id)?.title}</strong><p>Total: {dollars(invoice.total_cents/100)} · Paid: {dollars(received(invoice.id)/100)}<br/>Balance: {dollars(Math.max(0,invoice.total_cents-received(invoice.id))/100)} · Due: {invoice.due_date||"Not specified"}</p></div>)}</>}</div>;
}
