"use client";
import Script from "next/script";
import {useEffect,useMemo,useRef,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {addressKey,reusableLocation,type AddressLocation} from "@/lib/geocoding";
// Leaflet is loaded only when the Customer Map tab is opened.
declare global{interface Window{L?:any;}}
type Customer={id:string;name:string;address:string;status:string;phone:string};
const colors:Record<string,string>={"New Lead":"#38bdf8",Inspection:"#fbbf24","Estimate Sent":"#c084fc",Won:"#34d399",Lost:"#94a3b8"};
export default function CustomerMap({customers,userId,onOpen}:{customers:Customer[];userId:string|null;onOpen:(tab:string,id:string)=>void}){
 const db=useMemo(()=>createClient(),[]);const container=useRef<HTMLDivElement>(null);const map=useRef<any>(null);const layer=useRef<any>(null);const markers=useRef<Map<string,any>>(new Map());const [ready,setReady]=useState(false);const [locations,setLocations]=useState<Record<string,AddressLocation>>({});const [errors,setErrors]=useState<Record<string,string>>({});const [pending,setPending]=useState("");const [filter,setFilter]=useState("All");const [retry,setRetry]=useState(0);const [message,setMessage]=useState("");
 useEffect(()=>{if(!ready||!container.current||!window.L)return;const L=window.L;map.current=L.map(container.current).setView([29.4241,-98.4936],10);L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map.current);layer.current=L.layerGroup().addTo(map.current);const instance=map.current;return()=>{instance.remove();map.current=null;layer.current=null;};},[ready]);
 useEffect(()=>{let active=true;const controller=new AbortController();setErrors({});setLocations({});setMessage("");async function load(){try{if(!db||!userId)throw Error("Sign in to show customer locations.");
 const {data:sessionData}=await db.auth.getSession();const token=sessionData.session?.access_token;if(!token)throw Error("Sign in to show customer locations.");
 // Render valid cached pins immediately, then locate new or changed addresses one at a time.
 let cache:AddressLocation[]=[];for(let offset=0;;offset+=1000){const {data,error}=await db.from("customer_locations").select("lead_id,source_address,matched_address,lat,lng,status,checked_at").eq("user_id",userId).order("lead_id").range(offset,offset+999);if(error)throw error;cache.push(...data as AddressLocation[]);if(data.length<1000)break;}
 if(!active)return;setLocations(Object.fromEntries(cache.filter(l=>customers.some(c=>c.id===l.lead_id&&addressKey(c.address)===addressKey(l.source_address))).map(l=>[l.lead_id,l])));
 for(const c of customers){if(!active)break;if(!c.address.trim())continue;const existing=cache.find(l=>l.lead_id===c.id);if(existing&&reusableLocation(existing,c.address)&&!(retry>0&&existing.status!=="matched"))continue;setPending(c.id);try{const response=await fetch("/api/customer-map",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({leadId:c.id,retryNotFound:retry>0}),signal:controller.signal});const result=await response.json();if(!response.ok)throw Error(result.error||"Address lookup failed.");if(active)setLocations(current=>({...current,[c.id]:result.location as AddressLocation}));}catch(e){if(!active)break;setErrors(current=>({...current,[c.id]:e instanceof Error?e.message:"Could not locate address."}));}}
 }catch(e){if(active)setMessage(e instanceof Error?e.message:"Could not load map.");}finally{if(active)setPending("");}}void load();return()=>{active=false;controller.abort();};},[customers,userId,db,retry]);
 const visible=customers.filter(c=>filter==="All"||c.status===filter);const pins=visible.filter(c=>locations[c.id]?.status==="matched");
 useEffect(()=>{if(!ready||!map.current||!layer.current||!window.L)return;const L=window.L;layer.current.clearLayers();markers.current.clear();for(const c of pins){const location=locations[c.id];const popup=document.createElement("div");const title=document.createElement("strong");title.textContent=c.name;popup.append(title);const address=document.createElement("p");address.textContent=c.address+" · "+c.status;popup.append(address);const actions=document.createElement("div");const open=document.createElement("button");open.textContent="Open customer";open.addEventListener("click",()=>onOpen("Customer Workspace",c.id));actions.append(open);const directions=document.createElement("a");directions.textContent=" Directions";directions.href="https://www.google.com/maps/dir/?api=1&destination="+encodeURIComponent(c.address);directions.target="_blank";directions.rel="noreferrer";actions.append(directions);popup.append(actions);const marker=L.circleMarker([location.lat,location.lng],{radius:9,color:"#fff",weight:2,fillColor:colors[c.status]||"#38bdf8",fillOpacity:.95}).bindPopup(popup).addTo(layer.current);markers.current.set(c.id,marker);}if(pins.length){map.current.fitBounds(L.latLngBounds(pins.map(c=>[locations[c.id].lat,locations[c.id].lng])),{padding:[30,30],maxZoom:15});}},[ready,locations,customers,filter,onOpen]);
 function focus(id:string){const location=locations[id];if(!map.current||location?.status!=="matched")return;map.current.setView([location.lat,location.lng],16);markers.current.get(id)?.openPopup();}
 return <div className="card"><h2>Customer map</h2><p className="muted">Your saved customer addresses appear as pins automatically. Update an address in Customers to relocate its pin.</p><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"/><Script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" onReady={()=>setReady(true)} onError={()=>setMessage("Map library could not load. Refresh and try again.")}/><div className="roofToolbar"><div className="field"><label htmlFor="map-status">Lead stage</label><select id="map-status" value={filter} onChange={e=>setFilter(e.target.value)}>{["All",...Object.keys(colors)].map(s=><option key={s}>{s}</option>)}</select></div><button className="mini" disabled={Boolean(pending)} onClick={()=>setRetry(n=>n+1)}>Refresh / retry lookups</button><span>{pins.length} pins · {visible.length} customers{pending?" · Locating addresses…":""}</span></div>{message&&<p className="notice" role="status">{message}</p>}<div ref={container} className="roofMap" style={{zIndex:0}} aria-label="Map of saved customer addresses"/>
 <div className="roofToolbar">{Object.entries(colors).map(([s,color])=><span key={s} className="badge"><span aria-hidden="true" style={{background:color,width:9,height:9,borderRadius:"50%",marginRight:6}}/>{s}</span>)}</div><p className="small muted">Pins show approximate address locations, not surveyed roof positions. Address lookup: US Census Bureau; map: OpenStreetMap.</p>
 {!customers.length&&<p>Add a customer with a complete street address to see a pin.</p>}{visible.map(c=>{const l=locations[c.id];const detail=!c.address.trim()?"Add a street address":errors[c.id]||(!l?pending===c.id?"Locating…":"Waiting for lookup":l.status==="matched"?"Located":l.status==="ambiguous"?"Multiple matches — check the saved address":"Address not found — check street, city, state and ZIP");return <div key={c.id} className="activityItem"><strong>{c.name}</strong><p>{c.address||"No address"}</p><p className="small muted">{detail}</p><div className="roofToolbar"><button className="mini" disabled={l?.status!=="matched"} onClick={()=>focus(c.id)}>Show pin</button><button className="mini" onClick={()=>onOpen("Customer Workspace",c.id)}>Open customer</button><a target="_blank" rel="noreferrer" href={"https://www.google.com/maps/dir/?api=1&destination="+encodeURIComponent(c.address)}>Directions</a></div></div>;})}</div>;
}
