"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Customer={id:string;name:string};
type Activity={id:string;lead_id:string;title:string;kind:string;due_at:string|null;completed:boolean};
type Task={id:string;title:string;task_date:string;task_time:string|null;completed:boolean};
type Job={id:string;lead_id:string;title:string;status:string;scheduled_date:string|null};
type Quote={id:string;lead_id:string;status:string};
type Invoice={id:string;job_id:string;number:string;total_cents:number;due_date:string|null};
type Payment={invoice_id:string;amount_cents:number};
type Data={activity:Activity[];tasks:Task[];jobs:Job[];quotes:Quote[];invoices:Invoice[];payments:Payment[]};
const empty:Data={activity:[],tasks:[],jobs:[],quotes:[],invoices:[],payments:[]};
const money=(cents:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(cents/100);
function dayKey(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;}
export default function DashboardOverview({customers,userId,cloudMode,onOpen}:{customers:Customer[];userId:string|null;cloudMode:boolean;onOpen:(tab:string,customerId?:string,day?:string)=>void}){
 const db=useMemo(()=>createClient(),[]);const [data,setData]=useState<Data>(empty);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [refresh,setRefresh]=useState(0);
 useEffect(()=>{let active=true;setLoading(true);setError("");setData(empty);async function load(){try{let result:Data;if(cloudMode){if(!db||!userId)throw new Error("Sign in to load your dashboard.");async function all(table:string,fields:string){const rows:unknown[]=[];let start=0;while(true){const result=await db!.from(table).select(fields).order("id").range(start,start+999);if(result.error)throw result.error;rows.push(...result.data);if(result.data.length<1000)return rows;start+=1000;}}
 const results=await Promise.all([all("customer_activity","id,lead_id,title,kind,due_at,completed"),all("personal_tasks","id,title,task_date,task_time,completed"),all("jobs","id,lead_id,title,status,scheduled_date"),all("estimates","id,lead_id,status"),all("invoices","id,job_id,number,total_cents,due_date"),all("invoice_payments","id,invoice_id,amount_cents")]);result={activity:results[0] as Activity[],tasks:results[1] as Task[],jobs:results[2] as Job[],quotes:results[3] as Quote[],invoices:results[4] as Invoice[],payments:results[5] as Payment[]};}else{const read=(key:string)=>JSON.parse(localStorage.getItem(key)||"[]");result={activity:[],tasks:read("richardcrm.personal-tasks.v1"),jobs:read("richardcrm.jobs.v1"),quotes:customers.flatMap(customer=>read("richardcrm.estimates.v1."+customer.id)),invoices:read("richardcrm.invoices.v1"),payments:read("richardcrm.invoice-payments.v1")};}if(active)setData(result);}catch(error){if(active)setError(error instanceof Error?error.message:"Could not load dashboard.");}finally{if(active)setLoading(false);}}void load();return()=>{active=false;};},[db,userId,cloudMode,customers,refresh]);
 const today=dayKey(new Date());const paidByInvoice=new Map<string,number>();for(const payment of data.payments)paidByInvoice.set(payment.invoice_id,(paidByInvoice.get(payment.invoice_id)||0)+payment.amount_cents);
 const balances=data.invoices.map(invoice=>({...invoice,balance:Math.max(0,invoice.total_cents-(paidByInvoice.get(invoice.id)||0))}));const unpaid=balances.filter(invoice=>invoice.balance>0);const overdue=unpaid.filter(invoice=>invoice.due_date&&invoice.due_date<today);const totalDue=unpaid.reduce((sum,invoice)=>sum+invoice.balance,0);const received=data.payments.reduce((sum,payment)=>sum+payment.amount_cents,0);const activeJobs=data.jobs.filter(job=>!["Completed","Cancelled"].includes(job.status));const personal=data.tasks.filter(task=>!task.completed&&task.task_date<=today).sort((a,b)=>a.task_date.localeCompare(b.task_date)||(a.task_time||"99").localeCompare(b.task_time||"99"));const activities=data.activity.filter(item=>!item.completed&&item.due_at&&item.kind!=="note").sort((a,b)=>a.due_at!.localeCompare(b.due_at!));const scheduled=activeJobs.filter(job=>job.scheduled_date).sort((a,b)=>a.scheduled_date!.localeCompare(b.scheduled_date!));const name=(id:string)=>customers.find(customer=>customer.id===id)?.name||"Customer";
 return <><div className="roofToolbar" style={{marginTop:20}}><h2>What needs attention</h2><button className="mini" disabled={loading} onClick={()=>setRefresh(value=>value+1)}>Refresh dashboard</button><button className="btn secondary" onClick={()=>onOpen("Calendar")}>Open calendar</button></div>{loading?<p role="status">Loading schedule and financial overview…</p>:error?<p className="notice" role="alert">{error}</p>:<><div className="grid stats"><div className="card"><div className="statTitle">Invoice balance due</div><div className="statValue">{money(totalDue)}</div><div className="statFoot">{unpaid.length} unpaid invoices</div><button className="mini" onClick={()=>onOpen("Invoices")}>View invoices</button></div><div className="card"><div className="statTitle">Payments recorded</div><div className="statValue">{money(received)}</div><div className="statFoot">All-time manual receipts, including deposits</div></div><div className="card"><div className="statTitle">Overdue invoices</div><div className="statValue">{overdue.length}</div><div className="statFoot">{money(overdue.reduce((sum,invoice)=>sum+invoice.balance,0))} past the due date</div></div><div className="card"><div className="statTitle">Active jobs</div><div className="statValue">{activeJobs.length}</div><div className="statFoot">Planning, scheduled or in progress</div><button className="mini" onClick={()=>onOpen("Jobs")}>View jobs</button></div></div>
 <div className="grid" style={{marginTop:18}}><div className="card"><h3>Personal tasks: today & overdue</h3>{!personal.length?<p className="muted">No unfinished tasks due today or earlier.</p>:personal.slice(0,6).map(task=><div className="kpi" key={task.id}><span><strong>{task.title}</strong><br/>{task.task_date}{task.task_date<today?" · Overdue":" · Today"} · {task.task_time?.slice(0,5)||"Any time"}</span><button className="mini" onClick={()=>onOpen("Daily Schedule",undefined,task.task_date)}>Open</button></div>)}{personal.length>6&&<p className="muted">Showing 6 of {personal.length} tasks.</p>}</div><div className="card"><h3>Appointments & follow-ups</h3>{!activities.length?<p className="muted">No unfinished dated customer activity.</p>:activities.slice(0,6).map(item=><div className="kpi" key={item.id}><span><strong>{item.title}</strong><br/>{name(item.lead_id)} · {item.kind==="appointment"?"Appointment":"Follow-up"}<br/>{new Date(item.due_at!).toLocaleString()}{new Date(item.due_at!)<new Date()?" · Past due":""}</span><button className="mini" onClick={()=>onOpen("Customer Workspace",item.lead_id)}>Open</button></div>)}{activities.length>6&&<p className="muted">Showing the earliest 6 of {activities.length} items.</p>}</div><div className="card"><h3>Installations</h3>{!scheduled.length?<p className="muted">No active jobs with an installation date.</p>:scheduled.slice(0,6).map(job=><div className="kpi" key={job.id}><span><strong>{job.title}</strong><br/>{name(job.lead_id)} · {job.scheduled_date}<br/>{job.status}{job.scheduled_date!<today?" · Date passed":""}</span><button className="mini" onClick={()=>onOpen("Jobs",job.lead_id)}>Open</button></div>)}</div><div className="card"><h3>Saved estimate statuses</h3><p className="small muted">Includes all saved quotes and revisions.</p>{["Draft","Sent","Accepted","Declined"].map(status=><div className="kpi" key={status}><span>{status}</span><strong>{data.quotes.filter(quote=>(quote.status||"Draft")===status).length}</strong></div>)}<button className="mini" onClick={()=>onOpen("Estimates")}>View estimates</button></div><div className="card"><h3>Overdue invoice details</h3>{!overdue.length?<p className="muted">No overdue invoice balances.</p>:overdue.sort((a,b)=>a.due_date!.localeCompare(b.due_date!)).slice(0,6).map(invoice=>{const job=data.jobs.find(job=>job.id===invoice.job_id);return <div className="kpi" key={invoice.id}><span><strong>Invoice {invoice.number}</strong><br/>{job?name(job.lead_id):"Customer"} · Due {invoice.due_date}<br/>{money(invoice.balance)}</span><button className="mini" onClick={()=>onOpen("Invoices",job?.lead_id)}>Open</button></div>;})}</div></div></>}</>;
}
