"use client";
import {useEffect,useMemo,useState} from "react";
import {latestUnanswered} from "@/lib/crmTools";
import {createClient} from "@/lib/supabase/client";
type Customer={id:string;name:string;phone:string;email:string;status:string};
type Task={id:string;lead_id:string;title:string;details:string;due_at:string;completed:boolean;kind:string};
type Quote={id:string;lead_id:string;status:string;created_at:string;status_updated_at?:string};
export default function FollowUps({customers,userId,onOpen}:{customers:Customer[];userId:string|null;onOpen:(tab:string,id:string)=>void}){
 const db=useMemo(()=>createClient(),[]);const [tasks,setTasks]=useState<Task[]>([]);const [quotes,setQuotes]=useState<Quote[]>([]);const [busy,setBusy]=useState(false);const [ready,setReady]=useState(false);const [message,setMessage]=useState("");const [days,setDays]=useState(7);const [showCompleted,setShowCompleted]=useState(false);const [editing,setEditing]=useState<Task|null>(null);
 useEffect(()=>{let active=true;async function load(){try{if(!db||!userId)throw Error("Sign in to use cloud follow-ups.");const fetchRows=async(table:string)=>{let all:unknown[]=[];for(let start=0;;start+=1000){const {data,error}=await db.from(table).select("*").eq("user_id",userId).order("created_at",{ascending:false}).order("id").range(start,start+999);if(error)throw error;all.push(...data);if(data.length<1000)break;}return all;};const [t,q]=await Promise.all([fetchRows("customer_activity"),fetchRows("estimates")]);if(active){setTasks((t as Task[]).filter(t=>t.kind==="task"));setQuotes(q as Quote[]);}}catch(e){if(active)setMessage(e instanceof Error?e.message:"Could not load reminders.");}finally{if(active)setReady(true);}}void load();return()=>{active=false;};},[db,userId]);
 async function save(form:FormData){if(!db||!userId)return;setBusy(true);try{const lead_id=String(form.get("customer"));if(!customers.some(c=>c.id===lead_id))throw Error("Choose a customer.");const date=new Date(String(form.get("due")));if(!Number.isFinite(date.getTime()))throw Error("Choose a valid follow-up date.");const record={lead_id,title:String(form.get("title")).trim(),details:String(form.get("details")||""),due_at:date.toISOString(),kind:"task",completed:editing?.completed||false};const query=editing?db.from("customer_activity").update(record).eq("id",editing.id):db.from("customer_activity").insert({...record,user_id:userId});const {data,error}=await query.select().single();if(error)throw error;setTasks(t=>[data as Task,...t.filter(x=>x.id!==data.id)]);setEditing(null);setMessage("Follow-up saved. It also appears in Customer Workspace and Calendar.");}catch(e){setMessage(e instanceof Error?e.message:"Could not save.");}finally{setBusy(false);}}
 async function toggle(task:Task){if(!db)return;setBusy(true);try{const {error}=await db.from("customer_activity").update({completed:!task.completed}).eq("id",task.id).select("id").single();if(error)throw error;setTasks(t=>t.map(x=>x.id===task.id?{...x,completed:!x.completed}:x));}catch(e){setMessage(e instanceof Error?e.message:"Could not update.");}finally{setBusy(false);}}
 const now=Date.now();const stale=latestUnanswered(quotes,new Set(customers.filter(c=>["Won","Lost"].includes(c.status)).map(c=>c.id)),days,now);
 return <div className="card"><h2>Follow-up reminders</h2><p className="muted">Reminders appear here and on your calendar when you open the CRM.</p>{message&&<p className="notice" role="status">{message}</p>}
 <form key={editing?.id||tasks.length} action={save}><fieldset disabled={busy||!ready||!db||!userId} style={{border:0,padding:0}}><legend>{editing?"Edit follow-up":"Schedule follow-up"}</legend><div className="formGrid"><div className="field"><label htmlFor="follow-customer">Customer</label><select id="follow-customer" name="customer" required defaultValue={editing?.lead_id||""}><option value="">Choose</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label htmlFor="follow-due">Due date / time</label><input id="follow-due" name="due" type="datetime-local" required defaultValue={editing?localTime(editing.due_at):""}/></div></div><div className="field"><label htmlFor="follow-title">Task</label><input id="follow-title" name="title" required maxLength={200} defaultValue={editing?.title||""}/></div><div className="field"><label htmlFor="follow-details">Notes</label><textarea id="follow-details" name="details" defaultValue={editing?.details||""}/></div><div className="roofToolbar"><button className="btn">Save follow-up</button>{editing&&<button type="button" className="mini" onClick={()=>setEditing(null)}>Cancel</button>}</div></fieldset></form>
 <h3>Due and upcoming</h3><label><input type="checkbox" checked={showCompleted} onChange={e=>setShowCompleted(e.target.checked)}/> Include completed</label>{tasks.filter(t=>showCompleted||!t.completed).sort((a,b)=>a.due_at.localeCompare(b.due_at)).map(t=><div className="activityItem" key={t.id}><button className="mini" disabled={busy} aria-label={(t.completed?"Reopen ":"Complete ")+t.title} onClick={()=>void toggle(t)}>{t.completed?"✓":"○"}</button> <strong>{t.title}</strong><p>{customers.find(c=>c.id===t.lead_id)?.name} · {new Date(t.due_at).toLocaleString()} {!t.completed&&new Date(t.due_at).getTime()<now&&<span className="badge">Overdue</span>}</p><p>{t.details}</p><button className="mini" disabled={busy} onClick={()=>setEditing(t)}>Edit</button> <button className="mini" onClick={()=>onOpen("Customer Workspace",t.lead_id)}>Open customer</button></div>)}{ready&&!tasks.some(t=>showCompleted||!t.completed)&&<p>No follow-ups in this view.</p>}
 <h3 style={{marginTop:24}}>Estimates awaiting a response</h3><div className="field"><label htmlFor="stale-days">Flag the latest sent estimate after</label><select id="stale-days" value={days} onChange={e=>setDays(Number(e.target.value))}>{[3,7,14,30].map(n=><option key={n} value={n}>{n} days</option>)}</select></div>{stale.map(q=><div className="activityItem" key={q.id}><strong>{customers.find(c=>c.id===q.lead_id)?.name}</strong><p>Sent {new Date(q.status_updated_at||q.created_at).toLocaleDateString()}</p><button className="mini" onClick={()=>onOpen("Estimates",q.lead_id)}>Open estimate</button> <button className="mini" onClick={()=>onOpen("Message Templates",q.lead_id)}>Prepare follow-up message</button></div>)}{ready&&!stale.length&&<p>No latest sent estimates past this threshold.</p>}</div>;
}
function localTime(iso:string){const date=new Date(iso);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);}
