"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Customer={id:string;name:string;address:string};
type Job={id:string;lead_id:string;title:string;status:string;scheduled_date:string|null;crew:string;materials:string;notes:string;checklist:Record<string,boolean>};
const stages=["Planning","Scheduled","In progress","Completed","Cancelled"];
const steps=["Materials ordered","Materials delivered","Installation complete","Cleanup complete","Final inspection"];
export default function Jobs({customers,userId,cloudMode}:{customers:Customer[];userId:string|null;cloudMode:boolean}){
 const db=useMemo(()=>createClient(),[]);const [jobs,setJobs]=useState<Job[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [editing,setEditing]=useState<Job|null>(null);const [open,setOpen]=useState(false);const [filter,setFilter]=useState("Active");
 useEffect(()=>{let active=true;async function load(){setLoading(true);try{if(cloudMode){if(!db||!userId)throw new Error("Sign in to view jobs.");const {data,error}=await db.from("jobs").select("id,lead_id,title,status,scheduled_date,crew,materials,notes,checklist").order("created_at",{ascending:false});if(error)throw error;if(active)setJobs(data as Job[]);}else{const stored=localStorage.getItem("richardcrm.jobs.v1");if(active)setJobs(stored?JSON.parse(stored):[]);}}catch(error){if(active)setMessage(error instanceof Error?error.message:"Could not load jobs.");}finally{if(active)setLoading(false);}}void load();return()=>{active=false;};},[db,userId,cloudMode]);
 async function persist(job:Job,remove=false){setBusy(true);setMessage("");try{if(cloudMode){if(!db||!userId)throw new Error("Sign in before saving.");const query=remove?db.from("jobs").delete().eq("id",job.id):jobs.some(item=>item.id===job.id)?db.from("jobs").update({...job,updated_at:new Date().toISOString()}).eq("id",job.id):db.from("jobs").insert({...job,user_id:userId});const {error}=await query.select("id").single();if(error)throw error;}
 const next=remove?jobs.filter(item=>item.id!==job.id):jobs.some(item=>item.id===job.id)?jobs.map(item=>item.id===job.id?job:item):[job,...jobs];if(!cloudMode)localStorage.setItem("richardcrm.jobs.v1",JSON.stringify(next));setJobs(next);setMessage(remove?"Job deleted.":"Job saved.");return true;}catch(error){setMessage(error instanceof Error?error.message:"Could not save job.");return false;}finally{setBusy(false);}}
 async function save(form:FormData){const job:Job={id:editing?.id||crypto.randomUUID(),lead_id:String(form.get("customer")||""),title:String(form.get("title")||"").trim(),status:String(form.get("status")||"Planning"),scheduled_date:String(form.get("date")||"")||null,crew:String(form.get("crew")||""),materials:String(form.get("materials")||""),notes:String(form.get("notes")||""),checklist:editing?.checklist||{}};if(!job.title||!customers.some(item=>item.id===job.lead_id)){setMessage("Choose a customer and enter a job name.");return;}if(await persist(job)){setOpen(false);setEditing(null);}}
 const visible=jobs.filter(job=>filter==="All" ? true : filter==="Active" ? !["Completed","Cancelled"].includes(job.status) : job.status===filter);
 return <div className="card"><h2>Roofing jobs</h2><p className="muted">Track installation separately from the sales pipeline. Create a job after confirming the scope with your customer.</p><div className="roofToolbar"><button className="btn" disabled={busy||loading||!customers.length} onClick={()=>{setEditing(null);setOpen(true);}}>New job</button><div className="field"><label htmlFor="job-filter">Show</label><select id="job-filter" value={filter} onChange={event=>setFilter(event.target.value)}>{["Active","All",...stages].map(stage=><option key={stage}>{stage}</option>)}</select></div></div>{message&&<p className="notice" role="status">{message}</p>}
 {open&&<form key={editing?.id||"new"} action={save}><fieldset disabled={busy} style={{border:0,padding:0}}><div className="field"><label htmlFor="job-customer">Customer</label><select id="job-customer" name="customer" required defaultValue={editing?.lead_id||""}><option value="">Choose a customer</option>{customers.map(customer=><option key={customer.id} value={customer.id}>{customer.name} — {customer.address}</option>)}</select></div><div className="field"><label htmlFor="job-title">Job name</label><input id="job-title" name="title" required maxLength={200} defaultValue={editing?.title||""}/></div><div className="roofToolbar"><div className="field"><label htmlFor="job-status">Progress</label><select id="job-status" name="status" defaultValue={editing?.status||"Planning"}>{stages.map(stage=><option key={stage}>{stage}</option>)}</select></div><div className="field"><label htmlFor="job-date">Installation date (optional)</label><input id="job-date" name="date" type="date" defaultValue={editing?.scheduled_date||""}/></div></div>{["crew","materials","notes"].map(field=><div className="field" key={field}><label htmlFor={"job-"+field}>{field==="crew"?"Crew / installer":field==="materials"?"Materials and ordering notes":"Job notes"}</label><textarea id={"job-"+field} name={field} defaultValue={editing?.[field as "crew"|"materials"|"notes"]||""}/></div>)}<div className="roofToolbar"><button className="btn">{busy?"Saving…":"Save job"}</button><button className="btn secondary" type="button" onClick={()=>{setOpen(false);setEditing(null);}}>Cancel</button></div></fieldset></form>}
 {loading?<p>Loading jobs…</p>:!visible.length?<p className="muted">No jobs in this view.</p>:visible.map(job=>{const customer=customers.find(item=>item.id===job.lead_id);return <div className="card" key={job.id} style={{marginTop:16}}><h3>{job.title}</h3><p>{customer?.name||"Customer unavailable"} — {customer?.address}</p><strong>{job.status}</strong><p className="muted">Installation: {job.scheduled_date||"Not scheduled"}</p>{job.crew&&<p style={{whiteSpace:"pre-wrap"}}>Crew: {job.crew}</p>}{job.materials&&<p style={{whiteSpace:"pre-wrap"}}>Materials: {job.materials}</p>}{job.notes&&<p style={{whiteSpace:"pre-wrap"}}>{job.notes}</p>}<fieldset disabled={busy||open} style={{border:0,padding:0}}><legend>Job checklist</legend>{steps.map(step=><label key={step} style={{display:"block",margin:"10px 0"}}><input type="checkbox" checked={Boolean(job.checklist[step])} onChange={event=>void persist({...job,checklist:{...job.checklist,[step]:event.target.checked}})}/> {step}</label>)}</fieldset><div className="roofToolbar"><button className="mini" disabled={busy} onClick={()=>{setEditing(job);setOpen(true);}}>Edit job</button><button className="mini" disabled={busy} onClick={()=>{if(window.confirm("Delete this job and its checklist?"))void persist(job,true);}}>Delete job</button></div></div>;})}</div>;
}
