"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Item={id:string;description:string;quantity:number;rate:number};
type Template={id:string;name:string;items:Item[]};
export default function MaterialTemplates({userId,cloudMode,items,disabled,onApply}:{userId:string|null;cloudMode:boolean;items:Item[];disabled:boolean;onApply:(items:Item[])=>void}){
 const db=useMemo(()=>createClient(),[]);const [templates,setTemplates]=useState<Template[]>([]);const [name,setName]=useState("");const [chosen,setChosen]=useState("");const [busy,setBusy]=useState(false);const [ready,setReady]=useState(false);const [message,setMessage]=useState("");
 useEffect(()=>{let active=true;async function load(){setReady(false);try{if(cloudMode){if(!db||!userId)throw new Error("Sign in to load templates.");const {data,error}=await db.from("material_templates").select("id,name,items").order("name");if(error)throw error;if(active)setTemplates(data as Template[]);}else{const stored=localStorage.getItem("richardcrm.material-templates.v1");if(active)setTemplates(stored?JSON.parse(stored):[]);}if(active)setReady(true);}catch(error){if(active)setMessage(error instanceof Error?error.message:"Could not load templates.");}}void load();return()=>{active=false;};},[db,userId,cloudMode]);
 async function save(){if(!name.trim()||!items.length||items.some(item=>!item.description.trim()||!Number.isFinite(item.quantity)||item.quantity<=0||!Number.isFinite(item.rate)||item.rate<0)){setMessage("Enter a template name and valid estimate line items first.");return;}setBusy(true);try{const template:Template={id:crypto.randomUUID(),name:name.trim(),items:items.map(item=>({...item}))};if(cloudMode){if(!db||!userId)throw new Error("Sign in before saving templates.");const {error}=await db.from("material_templates").insert({...template,user_id:userId});if(error)throw error;}const updated=[...templates,template];if(!cloudMode)localStorage.setItem("richardcrm.material-templates.v1",JSON.stringify(updated));setTemplates(updated);setName("");setChosen(template.id);setMessage("Template saved. It includes these quantities and prices; review both for every new roof.");}catch(error){setMessage(error instanceof Error?error.message:"Could not save template.");}finally{setBusy(false);}}
 async function remove(){const template=templates.find(item=>item.id===chosen);if(!template||!window.confirm(`Delete template “${template.name}”? Saved estimates will stay unchanged.`))return;setBusy(true);try{if(cloudMode){if(!db||!userId)throw new Error("Sign in before deleting.");const {error}=await db.from("material_templates").delete().eq("id",chosen).select("id").single();if(error)throw error;}const updated=templates.filter(item=>item.id!==chosen);if(!cloudMode)localStorage.setItem("richardcrm.material-templates.v1",JSON.stringify(updated));setTemplates(updated);setChosen("");setMessage("Template deleted.");}catch(error){setMessage(error instanceof Error?error.message:"Could not delete template.");}finally{setBusy(false);}}
 return <fieldset disabled={disabled||busy||!ready} style={{margin:"20px 0",border:"1px solid #ccc",borderRadius:12,padding:16}}><legend>Reusable material templates</legend><p className="muted">Save the builder’s line items as a named package. Applying a template adds its stored quantities and prices; review them for this job. Quantities are not automatically calculated.</p><div className="field"><label htmlFor="template-name">New template name</label><input id="template-name" maxLength={100} value={name} onChange={event=>setName(event.target.value)}/></div><button type="button" className="mini" disabled={!items.length} onClick={()=>void save()}>Save current items as template</button><div className="field" style={{marginTop:12}}><label htmlFor="material-template">Saved template</label><select id="material-template" value={chosen} onChange={event=>setChosen(event.target.value)}><option value="">Choose a template</option>{templates.map(template=><option key={template.id} value={template.id}>{template.name}</option>)}</select></div><div className="roofToolbar"><button type="button" className="mini" disabled={!chosen} onClick={()=>{const template=templates.find(item=>item.id===chosen);if(template){onApply(template.items.map(item=>({...item,id:crypto.randomUUID()})));setMessage("Template items added. Check quantities and pricing before saving your estimate.");}}}>Add template items</button><button type="button" className="mini" disabled={!chosen} onClick={()=>void remove()}>Delete template</button></div>{message&&<p className="notice" role="status">{message}</p>}</fieldset>;
}
