"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Customer={id:string;name:string;phone:string;address:string};
const defaults=[{title:"Inspection scheduling",body:"Hi {name}, this is Star Roofing. When would be a good time to inspect your roof at {address}?"},{title:"Estimate follow-up",body:"Hi {name}, checking in on your roofing estimate. Do you have any questions about the scope or pricing? — Star Roofing"},{title:"Installation reminder",body:"Hi {name}, your roof installation is scheduled for {date}. Please keep the driveway clear and let us know if you have questions. — Star Roofing"},{title:"Review request",body:"Hi {name}, thank you for choosing Star Roofing! We'd appreciate an honest review of your experience: {review_link}"}];
type Template={id:string;title:string;payload:{body:string}};
export default function MessageTemplates({customers,userId,initialCustomerId=""}:{customers:Customer[];userId:string|null;initialCustomerId?:string}){
 const db=useMemo(()=>createClient(),[]);const [leadId,setLeadId]=useState(initialCustomerId);const [saved,setSaved]=useState<Template[]>([]);const [title,setTitle]=useState(defaults[0].title);const [body,setBody]=useState(defaults[0].body);const [date,setDate]=useState("");const [review,setReview]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const customer=customers.find(c=>c.id===leadId);
 useEffect(()=>{let active=true;setSaved([]);if(db&&userId&&leadId)void db.from("crm_records").select("id,title,payload").eq("lead_id",leadId).eq("kind","message").order("created_at",{ascending:false}).then(({data,error})=>{if(!active)return;if(error)setMessage(error.message);else setSaved(data as Template[]);});return()=>{active=false;};},[db,userId,leadId]);
 const text=body.replace(/\{(name|address|date|review_link)\}/g,(token,key)=>({name:customer?.name,address:customer?.address,date,review_link:review}[key as "name"|"address"|"date"|"review_link"]||token));
 async function save(){if(!db||!userId||!leadId||!title.trim()||!body.trim()){setMessage("Choose a customer and enter a title and message.");return;}setBusy(true);try{const {data,error}=await db.from("crm_records").insert({user_id:userId,lead_id:leadId,kind:"message",title:title.trim(),payload:{body}}).select("id,title,payload").single();if(error)throw error;setSaved(s=>[data as Template,...s]);setMessage("Template saved for this customer.");}catch(e){setMessage(e instanceof Error?e.message:"Could not save.");}finally{setBusy(false);}}
 async function remove(id:string){if(!db||!confirm("Delete this saved template?"))return;setBusy(true);try{const {error}=await db.from("crm_records").delete().eq("id",id).select("id").single();if(error)throw error;setSaved(s=>s.filter(t=>t.id!==id));}catch(e){setMessage(e instanceof Error?e.message:"Could not delete.");}finally{setBusy(false);}}
 return <div className="card"><h2>Message templates</h2><div className="field"><label htmlFor="message-customer">Customer</label><select id="message-customer" disabled={busy} value={leadId} onChange={e=>setLeadId(e.target.value)}><option value="">Choose a customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="roofToolbar">{defaults.map(t=><button className="mini" key={t.title} onClick={()=>{setTitle(t.title);setBody(t.body);}}>{t.title}</button>)}</div><div className="field"><label htmlFor="message-title">Template title</label><input id="message-title" maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></div><div className="field"><label htmlFor="message-body">Message — placeholders: {'{name}, {address}, {date}, {review_link}'}</label><textarea id="message-body" value={body} onChange={e=>setBody(e.target.value)}/></div><div className="formGrid"><div className="field"><label htmlFor="message-date">Installation date / time text</label><input id="message-date" value={date} onChange={e=>setDate(e.target.value)}/></div><div className="field"><label htmlFor="review-link">Your review link</label><input id="review-link" type="url" value={review} onChange={e=>setReview(e.target.value)}/></div></div><h3 style={{marginTop:18}}>Preview</h3><p style={{whiteSpace:"pre-wrap"}}>{text}</p><div className="roofToolbar"><button className="btn" disabled={!customer||/\{[^}]+\}/.test(text)} onClick={async()=>{try{await navigator.clipboard.writeText(text);setMessage("Copied. Paste it into your messaging app.");}catch{setMessage("Clipboard unavailable. Select and copy the preview text.");}}}>Copy message</button><button className="mini" disabled={busy} onClick={save}>Save customer template</button></div>{message&&<p className="notice" role="status">{message}</p>}<h3>Saved customer templates</h3>{saved.map(t=><div className="activityItem" key={t.id}><strong>{t.title}</strong><div className="roofToolbar"><button className="mini" onClick={()=>{setTitle(t.title);setBody(t.payload.body);}}>Use / customize</button><button className="mini" disabled={busy} onClick={()=>void remove(t.id)}>Delete</button></div></div>)}<p className="muted">Copying prepares the message; send it from your own messaging app.</p></div>;
}
